rosenbrock: rosenbrock.cc
	g++ -std=c++11 -o rosenbrock rosenbrock.cc -I /usr/local/Cellar/eigen/3.3.4/include/eigen3

impact: ImpactOscillator.cc
	g++ -std=c++11 -o impact ImpactOscillator.cc -I /usr/local/Cellar/eigen/3.3.4/include/eigen3 -L /usr/local/Cellar/boost/1.69.0/include/boost
