rosenbrock: rosenbrock.cc
	g++ -std=c++11 -o rosenbrock rosenbrock.cc -I /usr/local/Cellar/eigen/3.3.4/include/eigen3

shm: simpleHarmonicMotion.cc
	g++ -std=c++11 -o shm simpleHarmonicMotion.cc -I /usr/local/Cellar/eigen/3.3.4/include/eigen3
